import { createContext, useContext } from 'react'

const T = {
  th: {
    /* ── Nav ── */
    nav_dashboard:  'แดชบอร์ด',
    nav_machines:   'เครื่องจักร',
    nav_cylinders:  'กระบอก',
    nav_workorders: 'ใบสั่งงาน',
    nav_pm:         'แผน PM',
    nav_pm_log:     'Log PM',
    nav_center_check: 'ประวัติเช็คศูนย์',
    nav_design_bom: 'Design/BOM',
    nav_spareparts: 'อะไหล่',
    nav_purchasing: 'จัดซื้อ',
    nav_stock:      'เคลื่อนไหวสต็อก',
    nav_reports:    'รายงาน',
    nav_logs:       'บันทึก',
    nav_users:      'ผู้ใช้งาน',
    nav_webbuilder:      'ตั้งค่าเว็บ',
    nav_settings:        'การตั้งค่า',
    nav_repair_requests: 'แจ้งซ่อม',

    /* ── Common ── */
    add:          'เพิ่ม',
    edit:         'แก้ไข',
    delete:       'ลบ',
    save:         'บันทึก',
    cancel:       'ยกเลิก',
    refresh:      'รีเฟรช',
    search:       'ค้นหา',
    loading:      'กำลังโหลด...',
    saving:       'กำลังบันทึก...',
    no_data:      'ไม่พบข้อมูล',
    actions:      'การดำเนินการ',
    status:       'สถานะ',
    priority:     'ความสำคัญ',
    remark:       'หมายเหตุ',
    all_status:   'ทุกสถานะ',
    logout:       'ออกจากระบบ',
    administrator:'ผู้ดูแลระบบ',
    platform:     'แพลตฟอร์ม CMMS',

    /* ── Dashboard ── */
    dash_total_mc:   'เครื่องจักรทั้งหมด',
    dash_breakdown:  'เครื่องเสีย',
    dash_open_wo:    'ใบสั่งงานที่เปิดอยู่',
    dash_pm_sched:   'PM กำหนดการ',
    dash_low_stock:  'สต็อกต่ำ',
    dash_running:    'เครื่องปกติ',
    dash_pm_overdue: 'PM เกินกำหนด',
    dash_recent_wo:  'ใบสั่งงานล่าสุด',
    dash_wo_table:   'ใบสั่งงานล่าสุด',
    dash_running_sub:'เดินเครื่อง',
    dash_overdue_sub:'เกินกำหนด',
    dash_out_sub:    'หมด',
    dash_latest_sub: 'รายการล่าสุด',

    /* ── Machines ── */
    mc_add:     'เพิ่มเครื่องจักร',
    mc_edit:    'แก้ไขเครื่องจักร',
    mc_del_confirm: 'ลบเครื่องจักรนี้?',
    mc_search:  'ค้นหา Mc, Location, Type...',
    mc_th_item:        'ลำดับ',
    mc_th_loc:         'ตำแหน่ง',
    mc_th_mc:          'รหัสเครื่อง',
    mc_th_watercheck:  'ตรวจน้ำ',
    mc_th_serial_old:  'ซีเรียลเดิม',
    mc_th_serial_new:  'ซีเรียลใหม่',
    mc_th_feeder:      'ฟีดเดอร์',
    mc_th_mfr:         'ผู้ผลิต',
    mc_th_type:        'ประเภท',
    mc_th_dia:         'เส้นผ่าศูนย์',
    mc_th_gauge:       'เกจ',
    mc_th_needle:      'เข็ม',
    mc_th_oil:         'น้ำมัน',
    mc_th_model:       'รุ่น',
    mc_th_model_inv:   'รุ่น Inverter',
    mc_th_sinker:      'ซิงเกอร์',
    mc_th_tape1:       'เทป 1',
    mc_th_tape2:       'เทป 2',
    mc_th_tape3:       'เทป 3',
    mc_th_tape4:       'เทป 4',
    mc_th_dial_front:  'ไดอัลหน้า',
    mc_th_dial_rear:   'ไดอัลหลัง',
    mc_th_leg1:        'ขา 1',
    mc_th_leg2:        'ขา 2',
    mc_th_leg3:        'ขา 3',
    mc_th_leg4:        'ขา 4',
    mc_th_remark:      'หมายเหตุ',
    mc_th_updated:     'อัพเดทล่าสุด',

    /* ── Cylinders ── */
    cyl_add:          'เพิ่ม Cylinder',
    cyl_edit:         'แก้ไข Cylinder',
    cyl_del_confirm:  'ลบ Cylinder นี้?',
    cyl_search:       'ค้นหา Serial, Machine, Type...',
    cyl_th_serial:    'ซีเรียลปัจจุบัน',
    cyl_th_loc:       'ตำแหน่ง',
    cyl_th_machine:   'เครื่องจักร',
    cyl_th_type:      'ประเภท',
    cyl_th_dia:       'เส้นผ่าศูนย์',
    cyl_th_gauge:     'เกจ',
    cyl_th_item:       'ลำดับ',
    cyl_th_standard:   'มาตรฐาน Mc',
    cyl_th_newmc:      'เครื่องปัจจุบัน',
    cyl_th_serial_old: 'ซีเรียลเดิม',
    cyl_th_serial_now: 'ซีเรียลปัจจุบัน',
    cyl_th_status_now: 'สถานะ/ซีเรียล',
    cyl_th_feeder:     'ฟีดเดอร์',
    cyl_th_mfr:        'ผู้ผลิต',
    cyl_th_needle:     'เข็ม',
    cyl_th_machine_ref:'อ้างอิงกระบอก',
    cyl_th_comment:    'หมายเหตุ',
    cyl_req:          'กรุณากรอกซีเรียลปัจจุบัน',

    /* ── Work Orders ── */
    wo_add:            'สร้าง WO',
    wo_edit:           'แก้ไขใบสั่งงาน',
    wo_create:         'สร้างใบสั่งงาน',
    wo_del_confirm:    'ลบใบสั่งงานนี้?',
    wo_search:         'ค้นหา KI, MC, Design, ช่าง...',
    wo_th_id:          'เลขใบสั่งงาน',
    wo_th_machine:     'เครื่องจักร',
    wo_th_problem:     'ปัญหา',
    wo_th_ki:          'KI',
    wo_th_mc:          'MC',
    wo_th_design:      'Design',
    wo_th_bom:         'BOM',
    wo_th_date_start:  'วันที่เริ่ม',
    wo_th_date_end:    'วันที่เสร็จ',
    wo_th_detail:      'รายละเอียด',
    wo_th_job_type:    'ประเภทงาน',
    wo_th_tech:        'ช่าง',
    wo_th_duration:    'ระยะเวลา (นาที)',
    wo_th_result_raw:  'ผลดิบ',
    wo_th_result_set:  'ผลเซ็ต',
    wo_th_result_dye:  'ผลย้อม',
    wo_th_result_fix:  'ผลฟิกซ์',
    wo_th_comment:     'หมายเหตุ',
    wo_th_updated:     'อัปเดตล่าสุด',
    wo_req:            'กรุณากรอก KI และ MC',

    /* ── PM Plan ── */
    pm_add:         'เพิ่มแผน PM',
    pm_edit:        'แก้ไขแผน PM',
    pm_del_confirm: 'ลบแผน PM นี้?',
    pm_search:      'ค้นหา Machine, Type, ช่าง...',
    pm_th_machine:  'เครื่องจักร',
    pm_th_type:     'PM Type',
    pm_th_dept:     'แผนก',
    pm_th_next:     'PM ครั้งถัดไป',
    pm_th_tech:     'ช่าง',
    pm_req:         'กรุณากรอก Machine MC และ Next PM Date',

    /* ── Spare Parts ── */
    sp_add:         'เพิ่มอะไหล่',
    sp_edit:        'แก้ไขอะไหล่',
    sp_del_confirm: 'ลบ Spare Part นี้?',
    sp_search:      'ค้นหารหัสอะไหล่, ชื่อ, หมวดหมู่...',
    sp_alert:       'มีอะไหล่ {n} รายการที่ stock ต่ำหรือหมด',
    sp_th_code:     'รหัสอะไหล่',
    sp_th_name_th:  'ชื่ออะไหล่เดิม',
    sp_th_name_en:  'ชื่ออะไหล่',
    sp_th_cat:      'หมวดหมู่',
    sp_th_stock:    'คงเหลือ',
    sp_th_min:      'ต่ำสุด',
    sp_th_price:    'ราคา/หน่วย',
    sp_req:         'กรุณากรอกรหัสอะไหล่และชื่ออะไหล่',

    /* ── Purchasing ── */
    po_add:         'สร้าง PO',
    po_edit:        'แก้ไข PO',
    po_create:      'สร้างใบสั่งซื้อ',
    po_del_confirm: 'ลบ PO นี้?',
    po_search:      'ค้นหาเลข PO, แหล่งที่มา...',
    po_th_no:       'เลข PO',
    po_th_supplier: 'แหล่งที่มา',
    po_th_order:    'วันที่สั่ง',
    po_th_expect:   'วันที่คาด',
    po_th_total:    'มูลค่ารวม',
    po_req:         'กรุณากรอกแหล่งที่มา',

    /* ── Stock Movement ── */
    sm_add:      'เพิ่มรายการ',
    sm_modal:    'เพิ่มรายการเคลื่อนไหวสต็อก',
    sm_search:   'ค้นหารหัสอะไหล่, เลขรายการ, ผู้ดำเนินการ...',
    sm_all_type: 'ทุกประเภท',
    sm_th_date:  'วันที่',
    sm_th_type:  'ประเภท',
    sm_th_name:  'ชื่ออะไหล่',
    sm_th_before:'ก่อน',
    sm_th_change:'เปลี่ยนแปลง',
    sm_th_after: 'หลัง',
    sm_th_ref:   'อ้างอิง',
    sm_th_by:    'ผู้ดำเนินการ',
    sm_req:      'กรุณากรอกรหัสอะไหล่และจำนวน',

    /* ── Reports ── */
    rpt_mc_status:  'สถานะเครื่องจักร',
    rpt_wo_status:  'สถานะใบสั่งงาน',
    rpt_pm_status:  'สถานะแผน PM',
    rpt_sp_status:  'สถานะอะไหล่',
    rpt_summary:    'สรุปตัวเลข',
    rpt_total_mc:   'เครื่องจักรทั้งหมด',
    rpt_running:    'เครื่องเดิน (RUNNING)',
    rpt_total_wo:   'WO ทั้งหมด',
    rpt_done_wo:    'WO เสร็จแล้ว',

    /* ── Logs ── */
    log_search:   'ค้นหา Module, User, Record...',
    log_th_time:  'เวลา',
    log_th_old:   'ค่าเดิม',
    log_th_new:   'ค่าใหม่',
    log_th_note:  'หมายเหตุ',

    /* ── Users ── */
    usr_add:         'เพิ่มผู้ใช้',
    usr_edit:        'แก้ไขผู้ใช้',
    usr_del_confirm: 'ลบผู้ใช้นี้?',
    usr_search:      'ค้นหาอีเมล, ชื่อ...',
    usr_all_role:    'ทุกบทบาท',
    usr_th_name:     'ชื่อ',
    usr_req:         'กรุณากรอกอีเมล',

    /* ── Settings ── */
    set_db_title:   'โปรเจกต์ Supabase',
    set_tables:     'ตาราง (Rows)',
    set_cur_user:   'ผู้ใช้ปัจจุบัน',
    set_change_pwd: 'เปลี่ยนรหัสผ่าน',
    set_pwd_label:  'รหัสผ่านใหม่ (อย่างน้อย 6 ตัว)',
    set_pwd_btn:    'เปลี่ยนรหัสผ่าน',
    set_pwd_ok:     'เปลี่ยนรหัสผ่านสำเร็จ ✓',
    set_pwd_short:  'ต้องมีอย่างน้อย 6 ตัว',
    set_pwd_req:    'กรุณากรอกรหัสผ่านใหม่',

    /* ── Login ── */
    login_btn:   'เข้าสู่ระบบ',
    login_doing: 'กำลังเข้าสู่ระบบ...',
    login_req:   'กรุณากรอกอีเมลและรหัสผ่าน',
    login_wrong: 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',

    /* ── Nav Sections ── */
    nav_sec_overview:   'ภาพรวม',
    nav_sec_operations: 'การดำเนินงาน',
    nav_sec_inventory:  'คลังสินค้า',
    nav_sec_analytics:  'วิเคราะห์',
    nav_sec_system:     'ระบบ',

    /* ── DetailDrawer Group Labels ── */
    dr_general_info:  'ข้อมูลทั่วไป',
    dr_specs:         'ข้อมูลเฉพาะ',
    dr_updated:       'อัปเดต',
    dr_main_info:     'ข้อมูลหลัก',
    dr_duration:      'ระยะเวลา',
    dr_results:       'ผลการดำเนินงาน',
    dr_details:       'รายละเอียด',
    dr_schedule:      'กำหนดการ',
    dr_part_info:     'ข้อมูลอะไหล่',
    dr_stock:         'สต็อก',
    dr_compat_mc:     'เครื่องที่ใช้ได้',
    dr_po_info:       'ข้อมูล PO',
    dr_dates:         'วันที่',
    dr_amount:        'ยอดเงิน',
    dr_movement:      'รายการเคลื่อนไหว',
    dr_quantity:      'จำนวน',
    dr_reference:     'อ้างอิง',
    dr_request_info:  'ข้อมูลคำขอ',
    dr_cylinder_info: 'ข้อมูลกระบอก',
    dr_problem:       'รายละเอียดปัญหา',
    dr_assignment:    'การมอบหมาย',
    dr_repair_result: 'ผลการซ่อม',

    /* ── Common Field Labels ── */
    field_unit:          'หน่วย',
    field_supplier:      'ผู้จัดจำหน่าย',
    field_warehouse:     'คลังสินค้า',
    field_requested_by:  'ผู้ขอ',
    field_approved_by:   'ผู้อนุมัติ',
    field_received_date: 'วันที่รับจริง',
    field_total:         'ยอดรวม',
    field_last_pm:       'PM ล่าสุด',
    field_est_hours:     'ชั่วโมงประมาณ',
    field_req_parts:     'อะไหล่ที่ต้องใช้',
    field_date_end:      'วันที่สิ้นสุด',
    field_updated_at:    'อัปเดตล่าสุด',
    field_machine_ki:    'เครื่อง KI',

    /* ── Repair Requests ── */
    rr_search:               'ค้นหา Serial, ผู้แจ้ง, ช่าง…',
    rr_showing:              'แสดง {shown} จาก {total} รายการ',
    rr_field_no:             'เลขที่',
    rr_field_created_at:     'วันที่แจ้ง',
    rr_field_problem:        'ปัญหา',
    rr_field_reported_by:    'ผู้แจ้ง',
    rr_field_approved_by:    'อนุมัติโดย',
    rr_field_approved_at:    'วันที่อนุมัติ',
    rr_field_approval_notes: 'หมายเหตุ Supervisor',
    rr_field_repair_details: 'รายละเอียดการซ่อม',
    rr_field_parts_used:     'อะไหล่ที่ใช้',
    rr_field_completed_by:   'ช่างที่ซ่อม',
    rr_field_completed_at:   'วันที่เสร็จ',
    rr_open_page:            'เปิดหน้าซ่อม',
    repair_status_pending:     'รอการอนุมัติ',
    repair_status_approved:    'อนุมัติแล้ว',
    repair_status_rejected:    'ไม่อนุมัติ',
    repair_status_in_progress: 'กำลังซ่อม',
    repair_status_completed:   'ซ่อมเสร็จ',
  },

  en: {
    /* ── Nav ── */
    nav_dashboard:  'Dashboard',
    nav_machines:   'Machines',
    nav_cylinders:  'Cylinders',
    nav_workorders: 'Work Orders',
    nav_pm:         'PM Plan',
    nav_pm_log:     'PM Log',
    nav_center_check: 'Center Checks',
    nav_design_bom: 'Design/BOM',
    nav_spareparts: 'Spare Parts',
    nav_purchasing: 'Purchasing',
    nav_stock:      'Stock Movement',
    nav_reports:    'Reports',
    nav_logs:       'Logs',
    nav_users:      'Users',
    nav_webbuilder:      'Web Builder',
    nav_settings:        'Settings',
    nav_repair_requests: 'Repair Requests',

    /* ── Common ── */
    add:          'Add',
    edit:         'Edit',
    delete:       'Delete',
    save:         'Save',
    cancel:       'Cancel',
    refresh:      'Refresh',
    search:       'Search',
    loading:      'Loading...',
    saving:       'Saving...',
    no_data:      'No data found',
    actions:      'Actions',
    status:       'Status',
    priority:     'Priority',
    remark:       'Remark',
    all_status:   'All Status',
    logout:       'Logout',
    administrator:'Administrator',
    platform:     'CMMS Platform',

    /* ── Dashboard ── */
    dash_total_mc:   'Total Machines',
    dash_breakdown:  'Breakdown',
    dash_open_wo:    'Open Work Orders',
    dash_pm_sched:   'PM Scheduled',
    dash_low_stock:  'Low Stock',
    dash_running:    'Running',
    dash_pm_overdue: 'PM Overdue',
    dash_recent_wo:  'Recent WO',
    dash_wo_table:   'Recent Work Orders',
    dash_running_sub:'Running',
    dash_overdue_sub:'Overdue',
    dash_out_sub:    'Out of stock',
    dash_latest_sub: 'Latest entries',

    /* ── Machines ── */
    mc_add:     'Add Machine',
    mc_edit:    'Edit Machine',
    mc_del_confirm: 'Delete this machine?',
    mc_search:  'Search Mc, Location, Type...',
    mc_th_item:        'No.',
    mc_th_loc:         'Location',
    mc_th_mc:          'Machine',
    mc_th_watercheck:  'Water Check',
    mc_th_serial_old:  'Old Serial',
    mc_th_serial_new:  'New Serial',
    mc_th_feeder:      'Feeder',
    mc_th_mfr:         'Manufacturer',
    mc_th_type:        'Type',
    mc_th_dia:         'Diameter',
    mc_th_gauge:       'Gauge',
    mc_th_needle:      'Needle',
    mc_th_oil:         'Oil',
    mc_th_model:       'Model',
    mc_th_model_inv:   'Inverter Model',
    mc_th_sinker:      'Sinker',
    mc_th_tape1:       'Tape 1',
    mc_th_tape2:       'Tape 2',
    mc_th_tape3:       'Tape 3',
    mc_th_tape4:       'Tape 4',
    mc_th_dial_front:  'Front Dial',
    mc_th_dial_rear:   'Rear Dial',
    mc_th_leg1:        'Leg 1',
    mc_th_leg2:        'Leg 2',
    mc_th_leg3:        'Leg 3',
    mc_th_leg4:        'Leg 4',
    mc_th_remark:      'Remark',
    mc_th_updated:     'Last Updated',

    /* ── Cylinders ── */
    cyl_add:          'Add Cylinder',
    cyl_edit:         'Edit Cylinder',
    cyl_del_confirm:  'Delete this cylinder?',
    cyl_search:       'Search Serial, Machine, Type...',
    cyl_th_serial:    'Serial NOW',
    cyl_th_loc:       'Location',
    cyl_th_machine:   'Machine',
    cyl_th_type:      'Type',
    cyl_th_dia:       'Diameter',
    cyl_th_gauge:     'Gauge',
    cyl_th_item:       'No.',
    cyl_th_standard:   'Standard (Mc)',
    cyl_th_newmc:      'Current Machine',
    cyl_th_serial_old: 'Serial OLD',
    cyl_th_serial_now: 'Serial NOW',
    cyl_th_status_now: 'Status/Serial',
    cyl_th_feeder:     'Feeder',
    cyl_th_mfr:        'Manufacturer',
    cyl_th_needle:     'Needle',
    cyl_th_machine_ref:'Cylinder Ref',
    cyl_th_comment:    'Comment',
    cyl_req:          'Please enter Serial NOW',

    /* ── Work Orders ── */
    wo_add:            'Create WO',
    wo_edit:           'Edit Work Order',
    wo_create:         'Create Work Order',
    wo_del_confirm:    'Delete this Work Order?',
    wo_search:         'Search KI, MC, Design, Tech...',
    wo_th_ki:          'KI',
    wo_th_mc:          'MC',
    wo_th_design:      'Design',
    wo_th_bom:         'BOM',
    wo_th_date_start:  'Date Start',
    wo_th_date_end:    'Date End',
    wo_th_detail:      'Detail',
    wo_th_job_type:    'Job Type',
    wo_th_tech:        'Technician',
    wo_th_duration:    'Duration (min)',
    wo_th_result_raw:  'Result Raw',
    wo_th_result_set:  'Result Set',
    wo_th_result_dye:  'Result Dye',
    wo_th_result_fix:  'Result Fix',
    wo_th_comment:     'Comment',
    wo_th_updated:     'Last Updated',
    wo_req:            'Please enter KI and MC',

    /* ── PM Plan ── */
    pm_add:         'Add PM Plan',
    pm_edit:        'Edit PM Plan',
    pm_del_confirm: 'Delete this PM plan?',
    pm_search:      'Search Machine, Type, Tech...',
    pm_th_machine:  'Machine',
    pm_th_type:     'PM Type',
    pm_th_dept:     'Department',
    pm_th_next:     'Next PM',
    pm_th_tech:     'Technician',
    pm_req:         'Please enter Machine MC and Next PM Date',

    /* ── Spare Parts ── */
    sp_add:         'Add Spare Part',
    sp_edit:        'Edit Spare Part',
    sp_del_confirm: 'Delete this spare part?',
    sp_search:      'Search Part Code, Name, Category...',
    sp_alert:       '{n} item(s) are low stock or out of stock',
    sp_th_code:     'Part Code',
    sp_th_name_th:  'Name (TH)',
    sp_th_name_en:  'Part Name',
    sp_th_cat:      'Category',
    sp_th_stock:    'Stock',
    sp_th_min:      'Min',
    sp_th_price:    'Unit Price',
    sp_req:         'Please enter Part Code and Part Name',

    /* ── Purchasing ── */
    po_add:         'Create PO',
    po_edit:        'Edit PO',
    po_create:      'Create Purchase Order',
    po_del_confirm: 'Delete this PO?',
    po_search:      'Search PO No., Supplier...',
    po_th_no:       'PO Number',
    po_th_supplier: 'Supplier',
    po_th_order:    'Order Date',
    po_th_expect:   'Expected Date',
    po_th_total:    'Total Amount',
    po_req:         'Please enter Supplier',

    /* ── Stock Movement ── */
    sm_add:      'Add Entry',
    sm_modal:    'Add Stock Movement',
    sm_search:   'Search Part Code, TXN ID, Operator...',
    sm_all_type: 'All Types',
    sm_th_date:  'Date',
    sm_th_type:  'Type',
    sm_th_name:  'Part Name',
    sm_th_before:'Before',
    sm_th_change:'Change',
    sm_th_after: 'After',
    sm_th_ref:   'Reference',
    sm_th_by:    'Performed By',
    sm_req:      'Please enter Part Code and Quantity',

    /* ── Reports ── */
    rpt_mc_status:  'Machine Status',
    rpt_wo_status:  'Work Order Status',
    rpt_pm_status:  'PM Plan Status',
    rpt_sp_status:  'Spare Parts Status',
    rpt_summary:    'Summary',
    rpt_total_mc:   'Total Machines',
    rpt_running:    'Running',
    rpt_total_wo:   'Total Work Orders',
    rpt_done_wo:    'Completed WOs',

    /* ── Logs ── */
    log_search:   'Search Module, User, Record...',
    log_th_time:  'Time',
    log_th_old:   'Old Value',
    log_th_new:   'New Value',
    log_th_note:  'Note',

    /* ── Users ── */
    usr_add:         'Add User',
    usr_edit:        'Edit User',
    usr_del_confirm: 'Delete this user?',
    usr_search:      'Search Email, Name...',
    usr_all_role:    'All Roles',
    usr_th_name:     'Name',
    usr_req:         'Please enter Email',

    /* ── Settings ── */
    set_db_title:   'Supabase Project',
    set_tables:     'Tables (Rows)',
    set_cur_user:   'Current User',
    set_change_pwd: 'Change Password',
    set_pwd_label:  'New Password (min 6 chars)',
    set_pwd_btn:    'Change Password',
    set_pwd_ok:     'Password changed successfully ✓',
    set_pwd_short:  'Must be at least 6 characters',
    set_pwd_req:    'Please enter a new password',

    /* ── Login ── */
    login_btn:   'Sign In',
    login_doing: 'Signing in...',
    login_req:   'Please enter Email and Password',
    login_wrong: 'Incorrect email or password',

    /* ── Nav Sections ── */
    nav_sec_overview:   'Overview',
    nav_sec_operations: 'Operations',
    nav_sec_inventory:  'Inventory',
    nav_sec_analytics:  'Analytics',
    nav_sec_system:     'System',

    /* ── DetailDrawer Group Labels ── */
    dr_general_info:  'General Info',
    dr_specs:         'Specifications',
    dr_updated:       'Updated',
    dr_main_info:     'Main Info',
    dr_duration:      'Duration',
    dr_results:       'Results',
    dr_details:       'Details',
    dr_schedule:      'Schedule',
    dr_part_info:     'Part Info',
    dr_stock:         'Stock',
    dr_compat_mc:     'Compatible Machines',
    dr_po_info:       'PO Info',
    dr_dates:         'Dates',
    dr_amount:        'Amount',
    dr_movement:      'Movement',
    dr_quantity:      'Quantity',
    dr_reference:     'Reference',
    dr_request_info:  'Request Info',
    dr_cylinder_info: 'Cylinder Info',
    dr_problem:       'Problem Details',
    dr_assignment:    'Assignment',
    dr_repair_result: 'Repair Results',

    /* ── Common Field Labels ── */
    field_unit:          'Unit',
    field_supplier:      'Supplier',
    field_warehouse:     'Warehouse',
    field_requested_by:  'Requested By',
    field_approved_by:   'Approved By',
    field_received_date: 'Received Date',
    field_total:         'Total',
    field_last_pm:       'Last PM',
    field_est_hours:     'Est. Hours',
    field_req_parts:     'Required Parts',
    field_date_end:      'End Date',
    field_updated_at:    'Last Updated',
    field_machine_ki:    'Machine KI',

    /* ── Repair Requests ── */
    rr_search:               'Search Serial, Reporter, Technician…',
    rr_showing:              'Showing {shown} of {total}',
    rr_field_no:             'Request No.',
    rr_field_created_at:     'Report Date',
    rr_field_problem:        'Problem',
    rr_field_reported_by:    'Reported By',
    rr_field_approved_by:    'Approved By',
    rr_field_approved_at:    'Approved Date',
    rr_field_approval_notes: 'Supervisor Notes',
    rr_field_repair_details: 'Repair Details',
    rr_field_parts_used:     'Parts Used',
    rr_field_completed_by:   'Completed By',
    rr_field_completed_at:   'Completed Date',
    rr_open_page:            'Open Repair Page',
    repair_status_pending:     'Pending',
    repair_status_approved:    'Approved',
    repair_status_rejected:    'Rejected',
    repair_status_in_progress: 'In Progress',
    repair_status_completed:   'Completed',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const lang = 'th'
  const toggle = () => {}
  const t = (key, vars) => {
    let str = T.th?.[key] ?? key
    if (vars) Object.entries(vars).forEach(([k, v]) => { str = str.replace(`{${k}}`, v) })
    return str
  }

  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useT = () => useContext(LanguageContext)
