import { getPartStockStatus } from './inventory'

const col = (key, label) => ({ key, label })

const stripMetaLine = (value = '', prefix = 'ImageUrl:') =>
  String(value || '')
    .split('\n')
    .filter((line) => !line.trim().startsWith(prefix))
    .join('\n')
    .trim()

const extractMetaLine = (value = '', prefix = 'ImageUrl:') => {
  const line = String(value || '').split('\n').find((item) => item.trim().startsWith(prefix))
  return line?.trim().slice(prefix.length).trim() || ''
}

const imageFromNote = (row = {}, noteKey = 'Remark') => row.ImageUrl || extractMetaLine(row[noteKey]) || ''

export const SHEET_EXPORTS = [
  {
    key: 'machines',
    sheetName: 'เครื่องจักร',
    columns: [
      col('ITEM', 'ลำดับ'),
      col('Location', 'ตำแหน่ง'),
      col('Mc', 'รหัสเครื่อง'),
      col('WaterCheck', 'เช็คน้ำ'),
      col('Serial_OLD', 'ซีเรียลเดิม'),
      col('Serial_NEW', 'ซีเรียลใหม่'),
      col('Feeder', 'ฟีดเดอร์'),
      col('Manufacturer', 'ผู้ผลิต'),
      col('Type', 'ประเภท'),
      col('Diameter', 'เส้นผ่าศูนย์'),
      col('Gauge', 'เกจ'),
      col('Needle', 'เข็ม'),
      col('Oil', 'น้ำมัน'),
      col('Model', 'รุ่น'),
      col('Model_Inverter', 'รุ่น Inverter'),
      col('Sinker', 'Sinker'),
      col('Tape1_No', 'Tape 1'),
      col('Tape2_No', 'Tape 2'),
      col('Tape3_No', 'Tape 3'),
      col('Tape4_No', 'Tape 4'),
      col('Dial_Front', 'Dial หน้า'),
      col('Dial_Rear', 'Dial หลัง'),
      col('Leg1', 'ขา 1'),
      col('Leg2', 'ขา 2'),
      col('Leg3', 'ขา 3'),
      col('Leg4', 'ขา 4'),
      col('Status', 'สถานะ'),
      col('Remark', 'หมายเหตุ'),
      col('ImageUrl', 'URL'),
      col('updated_at', 'อัปเดตล่าสุด'),
    ],
    valueGetters: {
      ImageUrl: (row) => imageFromNote(row, 'Remark'),
      Remark: (row) => stripMetaLine(row.Remark),
    },
  },
  {
    key: 'cylinders',
    sheetName: 'กระบอก',
    columns: [
      col('ITEM', 'ลำดับ'),
      col('Location', 'ตำแหน่งฟีดเดอร์'),
      col('Standard', 'มาตรฐาน Mc'),
      col('NewMC', 'เครื่องใหม่'),
      col('Serial_OLD', 'ซีเรียลเดิม'),
      col('Serial_NOW', 'ซีเรียลปัจจุบัน'),
      col('Status_Now', 'สถานะปัจจุบัน'),
      col('Feeder', 'ฟีดเดอร์'),
      col('Manufacturer', 'ผู้ผลิต'),
      col('Type', 'ประเภท'),
      col('Diameter', 'เส้นผ่าศูนย์'),
      col('Gauge', 'เกจ'),
      col('Needle', 'เข็ม'),
      col('Machine_Ref', 'อ้างอิงกระบอก'),
      col('Comment', 'หมายเหตุ'),
      col('ImageUrl', 'URL'),
      col('updated_at', 'อัปเดตล่าสุด'),
    ],
    valueGetters: {
      ImageUrl: (row) => imageFromNote(row, 'Comment'),
      Comment: (row) => stripMetaLine(row.Comment),
    },
  },
  {
    key: 'workorders',
    sheetName: 'Jobs',
    columns: [
      col('Job_ID', 'Job ID'),
      col('StartDate', 'Start Date'),
      col('StartTime', 'Start Time'),
      col('KI', 'KI'),
      col('MC', 'M/C'),
      col('Design', 'Design'),
      col('JobType', 'Job Type'),
      col('Technicians', 'Technicians'),
      col('Comment', 'Comment'),
      col('EndDate', 'End Date'),
      col('EndTime', 'End Time'),
      col('WorkingHoursDecimal', 'Working Hours Decimal'),
      col('WorkingDurationText', 'Working Duration Text'),
      col('Status', 'Status'),
      col('CreatedBy', 'Created By'),
      col('CompletedBy', 'Completed By'),
      col('updated_at', 'Updated At'),
    ],
  },
  {
    key: 'pmplans',
    sheetName: 'แผน PM',
    columns: [
      col('Machine_MC', 'เครื่องปัจจุบัน'),
      col('Machine_KI', 'ซีเรียลเดิม'),
      col('Department', 'แผนก'),
      col('PM_Type', 'รอบ PM'),
      col('Frequency_Type', 'ประเภทความถี่'),
      col('Frequency_Value', 'จำนวนวัน'),
      col('Last_PM_Date', 'PM ล่าสุด'),
      col('Next_PM_Date', 'PM ครั้งถัดไป'),
      col('Estimated_Hours', 'ชั่วโมงประเมิน'),
      col('Assigned_Tech', 'ช่าง'),
      col('Priority', 'ความสำคัญ'),
      col('Status', 'สถานะ'),
      col('Required_Parts', 'อะไหล่ที่ใช้'),
      col('Downtime_Plan', 'เวลาหยุดเครื่อง'),
      col('Remark', 'หมายเหตุ'),
      col('ImageUrl', 'URL'),
      col('updated_at', 'อัปเดตล่าสุด'),
    ],
    valueGetters: {
      ImageUrl: (row) => imageFromNote(row, 'Remark'),
      Remark: (row) => stripMetaLine(row.Remark),
    },
  },
  {
    key: 'designBom',
    sheetName: 'Design BOM',
    columns: [
      col('MC', 'MC'),
      col('Design', 'Design'),
      col('KI', 'KI'),
      col('BOM', 'BOM'),
      col('CL1', 'CL1'),
      col('CL2', 'CL2'),
      col('CL3', 'CL3'),
      col('CL4', 'CL4'),
      col('SP', 'SP'),
      col('SL1', 'SL1'),
      col('SL2', 'SL2'),
      col('SL3', 'SL3'),
      col('SL4', 'SL4'),
      col('ImageUrl', 'URL'),
      col('Comment', 'หมายเหตุ'),
      col('LastUpdated', 'อัปเดตล่าสุด'),
    ],
    valueGetters: {
      ImageUrl: (row) => imageFromNote(row, 'Comment'),
      Comment: (row) => stripMetaLine(row.Comment),
    },
  },
  {
    key: 'repairRequests',
    sheetName: 'แจ้งซ่อม',
    columns: [
      col('request_no', 'เลขที่แจ้งซ่อม'),
      col('status', 'สถานะ'),
      col('cylinder_serial', 'ซีเรียลกระบอก'),
      col('cylinder_location', 'ตำแหน่งกระบอก'),
      col('cylinder_standard', 'มาตรฐานกระบอก'),
      col('machine_mc', 'เครื่อง'),
      col('KI', 'KI'),
      col('reporter_name', 'ผู้แจ้ง'),
      col('problem', 'ปัญหา'),
      col('priority', 'ความสำคัญ'),
      col('assigned_to', 'ผู้รับผิดชอบ'),
      col('report_date', 'วันที่แจ้ง'),
      col('approve_date', 'วันที่อนุมัติ'),
      col('complete_date', 'วันที่เสร็จ'),
      col('note', 'หมายเหตุ'),
      col('updated_at', 'อัปเดตล่าสุด'),
    ],
  },
  {
    key: 'spareparts',
    sheetName: 'อะไหล่',
    columns: [
      col('Part_Code', 'รหัสอะไหล่'),
      col('Category', 'หมวดหมู่'),
      col('Part_Name_EN', 'ชื่ออะไหล่'),
      col('Unit', 'หน่วย'),
      col('Status', 'สถานะ'),
      col('Stock_Qty', 'คงเหลือ'),
      col('Min_Qty', 'ขั้นต่ำ'),
      col('Unit_Price', 'ราคา/หน่วย'),
      col('Location_Store', 'คลัง'),
      col('Supplier', 'ผู้ขาย'),
      col('Compatible_Machines', 'เครื่องที่ใช้ได้'),
      col('ImageUrl', 'URL'),
      col('Remark', 'หมายเหตุ'),
      col('updated_at', 'อัปเดตล่าสุด'),
    ],
    valueGetters: {
      Status: (row) => row.Status || getPartStockStatus(row.Stock_Qty, row.Min_Qty),
      ImageUrl: (row) => imageFromNote(row, 'Remark'),
      Remark: (row) => stripMetaLine(row.Remark),
    },
  },
  {
    key: 'purchaseorders',
    sheetName: 'จัดซื้อ',
    columns: [
      col('PO_Number', 'เลขที่ PO'),
      col('PO_Date', 'วันที่ PO'),
      col('Supplier', 'ผู้ขาย'),
      col('Status', 'สถานะ'),
      col('Category', 'หมวดหมู่'),
      col('Part_Code', 'รหัสอะไหล่'),
      col('Part_Name_EN', 'ชื่ออะไหล่'),
      col('Detail', 'รายละเอียด'),
      col('Qty', 'จำนวน'),
      col('UnitPrice', 'ราคา/หน่วย'),
      col('Total_Amount', 'ยอดรวม'),
      col('Expected_Date', 'วันที่คาดว่าจะได้รับ'),
      col('Received_Date', 'วันที่รับของ'),
      col('ImageUrl', 'URL'),
      col('Note', 'หมายเหตุ'),
      col('updated_at', 'อัปเดตล่าสุด'),
    ],
    valueGetters: {
      ImageUrl: (row) => imageFromNote(row, 'Note'),
      Note: (row) => stripMetaLine(row.Note),
    },
  },
  {
    key: 'stocktransactions',
    sheetName: 'เคลื่อนไหวสต็อก',
    columns: [
      col('TXN_ID', 'เลขที่รายการ'),
      col('TXN_Type', 'ประเภทรายการ'),
      col('Part_Code', 'รหัสอะไหล่'),
      col('Part_Name_EN', 'ชื่ออะไหล่'),
      col('Category', 'หมวดหมู่'),
      col('Qty_Before', 'ก่อนหน้า'),
      col('Qty_Change', 'จำนวนเปลี่ยนแปลง'),
      col('Qty_After', 'คงเหลือหลังทำรายการ'),
      col('Unit', 'หน่วย'),
      col('Unit_Price', 'ราคา/หน่วย'),
      col('Reference', 'อ้างอิง'),
      col('Location_Store', 'คลัง'),
      col('Performed_By', 'ผู้ทำรายการ'),
      col('ImageUrl', 'URL'),
      col('Note', 'หมายเหตุ'),
      col('created_at', 'วันที่ทำรายการ'),
      col('updated_at', 'อัปเดตล่าสุด'),
    ],
    valueGetters: {
      ImageUrl: (row) => imageFromNote(row, 'Note'),
      Note: (row) => stripMetaLine(row.Note),
    },
  },
  {
    key: 'needleConditions',
    sheetName: 'สภาพเข็ม',
    columns: [
      col('serial', 'ซีเรียล (Serial)'),
      col('machine_mc', 'เครื่อง (MC)'),
      col('location', 'ตำแหน่ง'),
      col('type', 'ประเภท'),
      col('counter', 'Counter ล่าสุด'),
      col('status', 'สภาพเข็ม'),
      col('needle_condition', 'รายละเอียดสภาพเข็ม'),
      col('doc_date', 'วันที่ตรวจล่าสุด'),
      col('inspector', 'ผู้ตรวจ'),
      col('images', 'รูปภาพ URL'),
      col('remark', 'หมายเหตุ'),
      col('updated_at', 'อัปเดตล่าสุด'),
    ],
    valueGetters: {
      images: (row) => (Array.isArray(row.images) ? row.images.join(', ') : row.images || ''),
    },
  },
]

